"""Adiciona tabelas completas

Revision ID: 0209f0b3a863
Revises: 1b60c3031ad2
Create Date: 2026-01-20 17:38:38.378798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0209f0b3a863'
down_revision: Union[str, Sequence[str], None] = '1b60c3031ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_debt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock_movements')
    op.add_column('boxes', sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('boxes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('markets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('markets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('markets', 'active')
    op.drop_column('payments', 'external_ref')
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_index('ix_products_code', table_name='products')
    op.drop_column('products', 'version')
    op.alter_column('sales', 'box_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('users_cpf_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_cpf_key', 'users', ['cpf'])
    op.drop_column('users', 'updated_at')
    op.alter_column('sales', 'box_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('products', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_products_code', 'products', ['code'], unique=False)
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    op.drop_column('products', 'updated_at')
    op.add_column('payments', sa.Column('external_ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markets', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('markets', 'updated_at')
    op.drop_column('markets', 'is_active')
    op.drop_column('boxes', 'created_at')
    op.drop_column('boxes', 'opening_balance')
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_movements_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_movements_pkey')
    )
    op.drop_table('ticket_messages')
    op.drop_table('tickets')
    op.drop_table('customers')
    # ### end Alembic commands ###
