"""add cost_price to stock_movements

Revision ID: 0ebd78f8580a
Revises: 306c85d0c15f
Create Date: 2026-01-21 20:54:26.631455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebd78f8580a'
down_revision: Union[str, Sequence[str], None] = '306c85d0c15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'cost_price')
    # ### end Alembic commands ###
