"""fiscal

Revision ID: 306c85d0c15f
Revises: b033437e97cc
Create Date: 2026-01-21 16:21:54.160869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306c85d0c15f'
down_revision: Union[str, Sequence[str], None] = 'b033437e97cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('certificate_path', sa.String(), nullable=False),
    sa.Column('certificate_password', sa.String(), nullable=False),
    sa.Column('csc_token', sa.String(), nullable=False),
    sa.Column('csc_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('default_ncm', sa.String(), nullable=True),
    sa.Column('default_cfop', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id')
    )
    op.create_table('terminals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('xml_url', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('emitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boxes', sa.Column('terminal_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'boxes', 'terminals', ['terminal_id'], ['id'])
    op.add_column('plans', sa.Column('max_terminals', sa.Integer(), nullable=False))
    op.drop_column('plans', 'max_boxes_per_market')
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.add_column('plans', sa.Column('max_boxes_per_market', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'max_terminals')
    op.drop_constraint(None, 'boxes', type_='foreignkey')
    op.drop_column('boxes', 'terminal_id')
    op.drop_table('invoices')
    op.drop_table('customer_ledger')
    op.drop_table('terminals')
    op.drop_table('fiscal_config')
    # ### end Alembic commands ###
