"""empty message

Revision ID: 4f18990ac8f9
Revises: 0209f0b3a863
Create Date: 2026-01-20 18:53:07.801391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f18990ac8f9'
down_revision: Union[str, Sequence[str], None] = '0209f0b3a863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plans', sa.Column('price_180days', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plans', sa.Column('price_annual', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('plans', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('plans', 'price_annual')
    op.drop_column('plans', 'price_180days')
    op.drop_column('plans', 'price_monthly')
    # ### end Alembic commands ###
