"""contabil

Revision ID: 740995c1fda9
Revises: 
Create Date: 2026-03-01 13:06:03.384427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740995c1fda9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_accounting_consolidations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_sales_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cogs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_expenses_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_entries_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_losses_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'date', name='uq_daily_consolidation_market_date')
    )
    op.create_index(op.f('ix_daily_accounting_consolidations_market_id'), 'daily_accounting_consolidations', ['market_id'], unique=False)
    op.create_table('monthly_accounting_closures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cogs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('operational_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'year_month', name='uq_monthly_closure_market_period')
    )
    op.create_index(op.f('ix_monthly_accounting_closures_market_id'), 'monthly_accounting_closures', ['market_id'], unique=False)
    op.add_column('sale_items', sa.Column('cost_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index('ix_sales_market_created_status', 'sales', ['market_id', 'created_at', 'status'], unique=False)
    op.create_index('ix_stock_movements_prod_type_date', 'stock_movements', ['product_id', 'movement_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_movements_prod_type_date', table_name='stock_movements')
    op.drop_index('ix_sales_market_created_status', table_name='sales')
    op.drop_column('sales', 'tax_amount')
    op.drop_column('sale_items', 'cost_price_snapshot')
    op.drop_index(op.f('ix_monthly_accounting_closures_market_id'), table_name='monthly_accounting_closures')
    op.drop_table('monthly_accounting_closures')
    op.drop_index(op.f('ix_daily_accounting_consolidations_market_id'), table_name='daily_accounting_consolidations')
    op.drop_table('daily_accounting_consolidations')
    # ### end Alembic commands ###
