"""Add active col to terminals

Revision ID: 7fd4676a4361
Revises: 0ebd78f8580a
Create Date: 2026-01-22 17:17:52.243465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd4676a4361'
down_revision: Union[str, Sequence[str], None] = '0ebd78f8580a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('box_movements_operator_id_fkey', 'box_movements', type_='foreignkey')
    op.drop_column('box_movements', 'operator_id')
    op.alter_column('boxes', 'terminal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('customer_ledger', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_products_market_id'), 'products', ['market_id'], unique=False)
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_market_id'), 'sales', ['market_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.add_column('terminals', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('terminals', 'is_active')
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('terminals', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('terminals', 'active')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_sales_market_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_index(op.f('ix_products_market_id'), table_name='products')
    op.alter_column('customer_ledger', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('boxes', 'terminal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('box_movements', sa.Column('operator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('box_movements_operator_id_fkey', 'box_movements', 'users', ['operator_id'], ['id'])
    # ### end Alembic commands ###
