"""atualizar_modelos_pdv

Revision ID: 9b6db108ff32
Revises: 4f18990ac8f9
Create Date: 2026-01-20 23:26:19.872880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b6db108ff32'
down_revision: Union[str, Sequence[str], None] = '4f18990ac8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boxes', sa.Column('operator_id', sa.UUID(), nullable=False))
    op.add_column('boxes', sa.Column('initial_balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('boxes', sa.Column('final_balance_reported', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('boxes', sa.Column('closing_observation', sa.Text(), nullable=True))
    op.add_column('boxes', sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint('boxes_current_operator_id_fkey', 'boxes', type_='foreignkey')
    op.create_foreign_key(None, 'boxes', 'users', ['operator_id'], ['id'])
    op.drop_column('boxes', 'created_at')
    op.drop_column('boxes', 'updated_at')
    op.drop_column('boxes', 'name')
    op.drop_column('boxes', 'current_operator_id')
    op.drop_column('boxes', 'opening_balance')
    op.create_unique_constraint(None, 'markets', ['document'])
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.alter_column('sale_items', 'product_name_snapshot',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('sales', sa.Column('acrescimo', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('sales', 'box_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_sales_offline_id', table_name='sales')
    op.create_unique_constraint(None, 'users', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_sales_offline_id', 'sales', ['offline_id'], unique=True)
    op.alter_column('sales', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'box_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('sales', 'acrescimo')
    op.alter_column('sale_items', 'product_name_snapshot',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_constraint(None, 'markets', type_='unique')
    op.add_column('boxes', sa.Column('opening_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('boxes', sa.Column('current_operator_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('boxes', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('boxes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('boxes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'boxes', type_='foreignkey')
    op.create_foreign_key('boxes_current_operator_id_fkey', 'boxes', 'users', ['current_operator_id'], ['id'])
    op.drop_column('boxes', 'difference')
    op.drop_column('boxes', 'closing_observation')
    op.drop_column('boxes', 'final_balance_reported')
    op.drop_column('boxes', 'initial_balance')
    op.drop_column('boxes', 'operator_id')
    op.drop_table('financial_transactions')
    op.drop_table('box_movements')
    # ### end Alembic commands ###
